[project]
name = "wikideepseek"
version = "0.1.0"
description = ""
authors = [
    {name = "Sweet_Sempai",email = "chcolatemilk00@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "openai (>=1.84.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
